/* Note: this file is generated by the SWATT PLAST package */
/* Manual modifications may lead to unintended behaviour */

#ifndef PLAST_USEDMODULES_H 
#define PLAST_USEDMODULES_H 

#define PLAST_LOCATION "D:/CLEAN_PLAST/Software/Library/"

#define ENABLE_PLAST_LDFPARSER

#endif 

